baseURL = 'https://anushavc.github.io/AnushaVermaChandraju_Portfolio/'
languageCode = 'en-us'
title = 'Anusha Verma Chandraju'
theme='hugo-theme-quint'


canonifyURLs = true
relativeURLs = false  # Ensures full URLs are generated
[[menu.main]]
  name = "Experience"
  url = "AnushaVermaChandraju_Portfolio/experience"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "AnushaVermaChandraju_Portfolio/projects"
  weight = 2

[[menu.main]]
  name = "Hackathons"
  url = "AnushaVermaChandraju_Portfolio/hackathons"
  weight = 3

[[menu.main]]
  name = "About"
  url = "AnushaVermaChandraju_Portfolio/about"
  weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"  # Ensure Goldmark is used
  [markup.goldmark.renderer]
    unsafe = true  # This allows raw HTML to be rendered


contact = "You can write me an [email](mailto:canushaverma@gmail.com)."



